export const GET_USERS = "[USERS] GET USERS";
export const SUCCESS_GET_USERS = "[USERS] SUCCESS GET USERS";
export const GET_USER = "[USERS] GET USER";
export const SUCCESS_GET_USER = "[USERS] SUCCESS GET USER";
export const LAST_REQUEST_SUCCESS = "[USERS] LAST REQUEST SUCCESS";
